apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  annotations:
    communication: |
      {
        "name": "database",
        "inbound": [
          {
            "service": "backend",
            "port": 5432
          }
        ],
        "outbound": []
      }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: myapp
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
