apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  annotations:
    communication: |
      {
        "name": "database",
        "inbound": [],
        "outbound": []
      }
spec:
  serviceName: "database"
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: ticketing
        - name: POSTGRES_USER
          value: ticket_user
        - name: POSTGRES_PASSWORD
          value: securepassword

