apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  annotations:
    communication: |
      {
        "name": "payment",
        "inbound": [],
        "outbound": [
          {"service": "database", "port": 5432}
        ]
      }
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment:latest
        ports:
        - containerPort: 8080

