apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  annotations:
    communication: |
      {
        "name": "user-management",
        "inbound": [],
        "outbound": [
          {"service": "database", "port": 5432}
        ]
      }
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management:latest
        ports:
        - containerPort: 8080

